-- FASE 3: Migración Multiempresa (Aditiva)
-- Mantiene compatibilidad total con N8N y V1.0.1

-- 1. Crear tabla de empresas (Tenants)
CREATE TABLE IF NOT EXISTS companies (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  branding_config jsonb,
  created_at timestamptz DEFAULT now()
);

-- Insertar la empresa original (Pionera) de forma idempotente para mantener la retrocompatibilidad
INSERT INTO companies (id, name) 
VALUES (1, 'FAIREX Original') 
ON CONFLICT (id) DO NOTHING;

-- 2. Migración de la tabla de usuarios
-- Ya existe una tabla pública 'users'. Para evitar confusión con 'auth.users'
-- y mantener todo limpio, la renombramos a 'profiles'.
ALTER TABLE IF EXISTS users RENAME TO profiles;

-- Si la tabla 'profiles' acaba de ser renombrada (o si se crea de cero),
-- aseguramos que tenga las columnas necesarias para multiempresa:
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_id int8 REFERENCES companies(id) DEFAULT 1;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role text DEFAULT 'agent';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- 3. Modificar tablas sagradas de forma ADITIVA
-- Añadimos company_id con DEFAULT 1 para que los webhooks actuales de N8N no fallen al omitir esta columna
ALTER TABLE lead_memory 
  ADD COLUMN IF NOT EXISTS company_id int8 REFERENCES companies(id) DEFAULT 1;

ALTER TABLE n8n_chat_histories 
  ADD COLUMN IF NOT EXISTS company_id int8 REFERENCES companies(id) DEFAULT 1;

-- 4. Actualizar las filas existentes (si las hay) para que pertenezcan a la empresa 1 explícitamente
UPDATE lead_memory SET company_id = 1 WHERE company_id IS NULL;
UPDATE n8n_chat_histories SET company_id = 1 WHERE company_id IS NULL;
UPDATE profiles SET company_id = 1 WHERE company_id IS NULL;

-- (Fin de FASE 3)
-- La seguridad RLS se implementará en la FASE 4.
